# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               adityagodbole
tagline:             ' <br>The horizon of many people is a circle of redius zero. They call it their point of view.'
description:         ''
url:                 'http://adityagodbole.github.io'
paginate:            5
excerpt_separator:   '<!--more-->'
# About/contact
author:
  name:              adityagodbole
  email:             code.aa@gdbl.me
markdown: kramdown
highlighter: pygments


# Custom vars
version:             1.0.0
