# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               adityagodbole
tagline:             ' <br>The horizon of many people is a circle of redius zero. They call it their point of view.'
description:         ''
url:                 ''
baseurl:             'adityagodbole.github.io'
paginate:            5

# About/contact
author:
  name:              adityagodbole
  email:             code.aa@gdbl.me

# Custom vars
version:             1.0.0
